swagger: "2.0"
info:
  title: Todo Service
  version: 1.0.0
host: "localhost:9001"
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /todos:
    get:
      operationId: ListTodos
      responses:
        "200":
          description: List of todos
          schema:
            $ref: "#/definitions/TodoList"
    post:
      operationId: PostTodo
      parameters:
        - $ref: "#/parameters/TodoPost"
      responses:
        "201":
          description: Created
          schema:
            $ref: "#/definitions/Todo"
    delete:
      operationId: DeleteTodos
      responses:
        "204":
          description: Ok
  /todos/{todoId}:
    parameters:
      - $ref: "#/parameters/TodoId"
    get:
      operationId: GetTodo
      responses:
        "200":
          description: Successful
          schema:
            $ref: "#/definitions/Todo"
        "404":
          description: Not found
    patch:
      operationId: PatchTodo
      parameters:
        - $ref: "#/parameters/TodoPatch"
      responses:
        "200":
          description: Successful
          schema:
            $ref: "#/definitions/Todo"
        "404":
          description: Not found
    delete:
      operationId: DeleteTodo
      responses:
        "204":
          description: Ok
        "404":
          description: Not found
parameters:
  TodoId:
    name: todoId
    in: path
    required: true
    type: integer
  TodoPost:
    name: todoPost
    in: body
    schema:
      type: object
      required:
        - title
      properties:
        title:
          type: string
  TodoPatch:
    name: TodoPatch
    in: body
    schema:
      type: object
      properties:
        title:
          type: string
        order:
          type: integer
        completed:
          type: boolean
definitions:
  TodoList:
    type: array
    items:
      $ref: "#/definitions/Todo"
  Todo:
    type: object
    required:
      - id
      - title
      - order
      - completed
      - url
    properties:
      id:
        type: integer
      title:
        type: string
      order:
        type: integer
      completed:
        type: boolean
      url:
        type: string
